Ensure that the MPS builds with "clang -Werror -Wcomma -std=c89"
Ravenbrook/mps pull request #48
Opened 2021-01-09 13:01 UTC by gareth-rees

The -Wcomma option appears to be turned on automatically by Xcode 12.3, so it's a good idea for the MPS to build with the option, to avoid unpleasant surprises when people update their Xcode.

The simplest way to suppress the warning is to cast the left hand side of the comma operator to void.

Fixes #47.

2021-01-10 11:04 UTC, rptb1 reviewed
This issue seems to occur exclusively where we have created `for` loops with more than one variable.  I'm wondering whether we shouldn't just ban those, because they are now hard to read.  They do, however, express something about the loop invariants that would be lost if we moved the variable updates out of the `for`. Opinions?

2021-01-10 11:17 UTC, gareth-rees commented
I considered moving some of the assignments out of the loops, but I decided against it because (i) it would make it harder to review; and (ii) the use of multiple variables in a loop expresses an intention (usually that the variables iterate together according to an invariant) that would be lost if we moved one of the variables out of the loop.

I am not averse to trying to refactor these loops, but I think it should be done in a separate issue and pull request. The problem being solved here is "MPS does not build in Xcode 12.3" and I think it is a better engineering approach to focus on solving the critical problem first, and the less critical problem (the code becomes somewhat harder to follow) in a separate step.

In most cases it looks to me as though a second loop variable has been introduced as a kind of hand-optimization, for example in amcsshe.c we have:
```
char *p = (char*)exactRoots[r];
for(i = 0; i < bogusRootsCOUNT; (void)(++i), ++p)
  bogusRoots[i] = (mps_addr_t)p;
```
where the increment of `p` on each loop is a kind of strength reduction optimization. But compilers are perfectly capable of doing that optimization themselves these days (when it is worth it), so we can write:
```
for(i = 0; i < bogusRootsCOUNT; ++i)
  bogusRoots[i] = (mps_addr_t)(p + i);
```
without any loss of performance (even if performance mattered here, which it almost certainly doesn't).

2021-01-10 14:58 UTC, gareth-rees commented
@rptb1 See the updated pull request — I've added a commit that refactors all the loops to improve maintainability, as requested.

2021-01-12 14:47 UTC, rptb1 commented
> In most cases it looks to me as though a second loop variable has been introduced as a kind of hand-optimization, for example in amcsshe.c we have ...

For future reference, you can select a line number range, "copy permalink", from code and paste that in, like this

https://github.com/Ravenbrook/mps/blob/d13e2855bfeceaa14b942e7b9e90af7a15de04ad/code/amcsshe.c#L195-L196

And then it can be clicked through.

2021-01-18 14:26 UTC, rptb1 requested changes
This is a good general cleanup.

2021-01-18 14:26 UTC, rptb1 commented on code/misc.h
> + * clang -Wcomma -std=c89.
```suggestion
 * clang -Wcomma -std=c89, while clearly expressing intention.  See
 * <https://github.com/Ravenbrook/mps/pull/48#issuecomment-757458796>.
```

2021-01-20 10:41 UTC, merged