Handle errors from mmap and mprotect due to Apple Hardened Runtime.
Ravenbrook/mps pull request #82
Opened 2022-12-22 19:18 UTC by gareth-rees

On Apple Silicon, when Hardened Runtime is in force and the applicateion lacks the "Allow Unsigned Executable Memory Entitlement", mmap and mprotect return EACCES when attempt is made to create or modify memory so that it is simultaneously writable and executable.

This commit handles these cases by retrying the operation without the PROT_EXEC flag, and setting global variables so that future operations omit the flag.

Fixes #75 (Issue with Apple silicon write-xor-execute memory requirements)

2023-01-04 15:24 UTC, thejayps requested changes
Joint review with @rptb1, @UNAA008 & @thejayps: 

This fundamentally changes the MPS' behaviour for the user on the Apple platform and this needs to be documented. Code should reference this documentation.

A requirement exists to support dynamically allocated code. If we can't fulfil this requirement on a hardened runtime platform or otherwise we must make sure this is clearly explained

2023-01-04 15:24 UTC, thejayps commented on code/protix.c
> +/* Value for memory protection corresponding to AccessSetEMPTY. */
Cross reference to paragraph below re conversion between MPS AccessSet and Unix Prot

2023-01-04 15:24 UTC, thejayps commented on code/vmix.c
> +/* Value to use for protection of newly allocated pages. */
Cross reference to analagous thing in protix.c and vice versa

2023-01-04 15:24 UTC, thejayps commented on code/vmix.c
General comment: Some comments from protix.c also apply to corresponding places in this file

2023-01-04 15:58 UTC, gareth-rees commented
> This fundamentally changes the MPS' behaviour for the user on the Apple platform

I think there has been a misunderstanding about the nature of the problem and the purpose of this pull request.

1. The MPS _does not support_ the XCA6LL platform: the latest release is 1.117.0 which does not compile or run on this platform. So there is _no behaviour to change_. This pull request is _one step towards_ implementing support for that platform, so that when you make release 1.118.0 we can announce that it supports XCA6LL.
2. This pull request does not prevent developers on XCA6LL from implementing dynamically allocated code in the MPS. These developers have a couple of other options: they can disable Hardened Runtime or add the Allow Unsigned Executable Memory Entitlement.
3. This pull request enables the MPS to work _in the common case_ where Hardened Runtime is enabled (as it is by default), the Allow Unsigned Executable Memory Entitlement is not configured (as it is not by default) and code does not need to be dynamically allocated (as in many or most programs).

Since this has been misunderstood, I will add some documentation to clarify these points.

2023-01-04 18:30 UTC, rptb1 commented
> I think there has been a misunderstanding about the nature of the problem and the purpose of this pull request.

I believe we understood everything you say, except the details about Unsigned Executable Memory Entitlement.

The MPS generally supports executable code on the heap.  The majority of MPS deployments rely on it (though not on XCA6LL of course).  If we introduce a platform where that spec is not met, we need to document that we have done that, even if briefly, and ensure that statement is traceable from the code.  I'm sure you're on it.

2023-01-04 18:39 UTC, rptb1 commented
> The MPS generally supports executable code on the heap.

As far as I can tell (well, as far as I can grep) we don't state this in the manual or design.  This pull request has raised the issue for the first time, because [Apple's Hardened Runtime](https://developer.apple.com/documentation/security/hardened_runtime) is the first platform where it's not trivial.

2023-01-04 18:42 UTC, NickBarnes commented
What could support for executable code on the heap look like? Can we sketch that out?
As I understand it, these Apple security changes don’t entirely prevent it, they simply outlaw W&X. So could we provide an API to do W -> X ? What might that look like?

> On 4 Jan 2023, at 18:31, Richard Brooksby ***@***.***> wrote:
> 
> ﻿
> I think there has been a misunderstanding about the nature of the problem and the purpose of this pull request.
> 
> I believe we understood everything you say, except the details about Unsigned Executable Memory Entitlement.
> 
> The MPS generally supports executable code on the heap. The majority of MPS deployments rely on it (though not on XCA6LL of course). If we introduce a platform where that spec is not met, we need to document that we have done that, even if briefly, and ensure that statement is traceable from the code. I'm sure you're on it.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

2023-01-04 18:48 UTC, NickBarnes commented
E.g. a pool class in which one allocates W & !X, and may force W -> X on an allocated object. MPS has to abandon (whatever that’s called; I’m rusty) any buffer on the same page, and of course the OS prohibits further writes so wouldn’t work for any language runtime or implementation which likes to write to fields in code objects, but presumably this is the sort of thing that language implementors are doing on W^X platforms.
Or am I completely misunderstanding?

> On 4 Jan 2023, at 18:42, Nick Barnes ***@***.***> wrote:
> 
> ﻿
> What could support for executable code on the heap look like? Can we sketch that out?
> As I understand it, these Apple security changes don’t entirely prevent it, they simply outlaw W&X. So could we provide an API to do W -> X ? What might that look like?
> 
>>> On 4 Jan 2023, at 18:31, Richard Brooksby ***@***.***> wrote:
>>> 
>> ﻿
>> I think there has been a misunderstanding about the nature of the problem and the purpose of this pull request.
>> 
>> I believe we understood everything you say, except the details about Unsigned Executable Memory Entitlement.
>> 
>> The MPS generally supports executable code on the heap. The majority of MPS deployments rely on it (though not on XCA6LL of course). If we introduce a platform where that spec is not met, we need to document that we have done that, even if briefly, and ensure that statement is traceable from the code. I'm sure you're on it.
>> 
>> —
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> You are receiving this because you are subscribed to this thread.

2023-01-04 18:52 UTC, rptb1 commented
> What could support for executable code on the heap look like? Can we sketch that out?

I'm not sure I understand this question.  Configura, for example, allocate objects on the heap in the AMC pool containing code compiled on-the-fly, which they then call.  Any JIT would need it.  (I'm not sure how Apple's system copes with JITs etc.)

2023-01-04 19:15 UTC, rptb1 commented
See https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-jit and specifically `MAP_JIT`.  I can't read all of this now, but the requirement for executable memory raises some issues that might affect this code.  In particular, this change uses global static variables to quietly and irreversibly change the nature of allocated memory.  Should the MPS have a proper interface declaring the intention to do JIT-like stuff on the heap?  Can restrictions change at run-time?  Other platforms might start introducing similar restrictions.

2023-01-04 19:20 UTC, thejayps commented
I understood NB's question to be assuming the hardened runtime scenario or
similar...

On Wed, 4 Jan 2023, 18:42 Nick Barnes, ***@***.***> wrote:

> What could support for executable code on the heap look like? Can we
> sketch that out?
> As I understand it, these Apple security changes don’t entirely prevent
> it, they simply outlaw W&X. So could we provide an API to do W -> X ? What
> might that look like?
>
> > On 4 Jan 2023, at 18:31, Richard Brooksby ***@***.***> wrote:
> >
> > ﻿
> > I think there has been a misunderstanding about the nature of the
> problem and the purpose of this pull request.
> >
> > I believe we understood everything you say, except the details about
> Unsigned Executable Memory Entitlement.
> >
> > The MPS generally supports executable code on the heap. The majority of
> MPS deployments rely on it (though not on XCA6LL of course). If we
> introduce a platform where that spec is not met, we need to document that
> we have done that, even if briefly, and ensure that statement is traceable
> from the code. I'm sure you're on it.
> >
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you are subscribed to this thread.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Ravenbrook/mps/pull/82#issuecomment-1371288892>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARN4DQKD34MILMX2KYK43IDWQXAB7ANCNFSM6AAAAAATHBKAIE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-04 20:59 UTC, gareth-rees commented on code/protix.c
> +    /* See <config.h#hardened-runtime>. */
The code base have 43 instances of a cross-reference with no space and no instances with a space, so for consistency I have gone with the majority.

2023-01-04 21:15 UTC, gareth-rees commented
I've addressed most of the review comments in the fixup commit. Still thinking about where to put the user documentation.

2023-01-04 21:15 UTC, NickBarnes commented
On 4 Jan 2023, at 18:52, Richard Brooksby wrote:

> > What could support for executable code on the heap look like? Can we 
> sketch that out?
>
> I'm not sure I understand this question.  Configura, for example, 
> allocate objects on the heap in the AMC pool containing code compiled 
> on-the-fly, which they then call.  Any JIT would need it.  (I'm not 
> sure how Apple's system copes with JITs etc.)

I mean, in the context of the Apple Hardened Runtime. There are clearly 
several ways to get chosen byte sequences into memory and execute them 
on W^X systems. For example, one could write code to a file (whether on 
a real filesystem or not - see also memfd_create() on Linux) and then 
map it in with MAP_EXEC. I'm a little curious about how the dynamic 
linker works on macOS with the Hardened Runtime, but I imagine it's 
similar to the way it does on Linux these days. Of course some programs 
will use MAP_JIT (for which they will have the necessary "entitlement" - 
I wonder what was wrong with the word "capability").

I approve of the general rule enforced by this aspect of the Hardened 
Runtime: "executable pages shouldn't be writable", also known as "W^X". 
There are ways of enforcing this general policy on loads of different 
OSes including Linuxes, BSDs, and Windows. So what I'm wondering is 
whether the MPS should offer some sort of support for clients who want 
to allocate objects in the arena which contain code which is 
subsequently executed, even on such W^X platforms.

For example, under the Apple Hardened Runtime, can one map anonymous 
pages for writing, write code to them, and then switch them from 
writable to executable before executing the code? (maybe one could even 
do this switch in the signal handler invoked when the 
not-actually-executable code is called, although that could be really 
messy if happening asynchronously with some other thread writing to the 
same page). If that is possible, as I believe it is on some other W^X 
systems, then a future MPS could potentially offer support for systems 
which want to do it (for example, a pool class which supports this 
behaviour somehow). There are a million details. For instance, you'd 
have to invalidate any buffer allocating on the page (segment?) in 
question.

This wouldn't work for language implementations which like to write to 
code objects which are already executable, but those design choices can, 
and probably should, be revisited (IIRC our LLVM backend does this or 
something like it for UNWIND_INFO, but I'm very rusty about all that).
—
Nick B

2023-01-04 21:21 UTC, NickBarnes commented
W^X was mainly developed to defend against attackers who are able (due to vulnerabilities) to write to some parts of memory which are executable (and which are then executed), but not able to make arbitrary calls to mmap(). Such attackers can't switch W -> X. This is believed, with some reason, to account for quite a lot of past security vulnerabilities.

2023-01-04 21:21 UTC, gareth-rees commented on design/prot.txt
> +simultaneously writable and executable. Moreoverm the feature is
Typo: "Moreoverm"

2023-01-04 21:21 UTC, gareth-rees commented on code/config.h
> + * mprotect() with PROT_WRITE | PROT_EXEC will fail with EACCES.
"may fail" would be better.

2023-01-04 21:21 UTC, gareth-rees commented on design/prot.txt
> +enabled by default in recent versions of Xcode, so that if you install
A version (e.g. "as of macOS 13 Ventura") would be more future-proof than "recent".

2023-01-04 22:00 UTC, gareth-rees commented
I added a "Limitations" section to the "Platforms" chapter of the Reference Manual, which seems like a plausible place people might look.

2023-01-05 11:50 UTC, thejayps reviewed
2nd review with @rptb1, @UNAA008 & @thejayps:

We think this all looks good but we are currently unable to approve because we can't build on all target platforms. Watch this space.

2023-01-06 17:48 UTC, rptb1 commented
The branch attached to this pull request doesn't fit with the MPS's durable branch naming scheme of branch/DATE/TOPIC.  This is an opportunity to figure out how renaming the branch affects the infrastructure (GitHub, Travis, etc.).  Please attempt it and say how you did it.

2023-01-06 18:24 UTC, gareth-rees commented
> The branch attached to this pull request doesn't fit with the MPS's durable branch naming scheme of branch/DATE/TOPIC

What branch name do you want?

2023-01-06 18:30 UTC, closed without merging

2023-01-06 18:34 UTC, gareth-rees commented
GitHub automatically closed the pull request when I renamed the branch. I made pull request #93 to replace this one.